In [1]:
from utils import dataloader

from tqdm import tqdm
from torch.utils.data import DataLoader

infer_list ="training.json" 
dataset_root ="images"

### Binary dataset  

In [2]:
databin = dataloader.ClassificationDataset(infer_list, dataset_root=dataset_root, binary=True)
print("Amount of images", len(databin))
num_classes_binary = databin.label_list.shape[1]
for img in tqdm(databin):
    print(img["name"])
    print(img["img"])
    print(img["label"])
    break

  0%|          | 0/7829 [00:00<?, ?it/s]

Amount of images 7829
3456.png
[[[ 70  72  70 ...  78  83  83]
  [ 71  67  68 ...  81  79  81]
  [ 72  68  62 ...  89  78  81]
  ...
  [ 88  78  80 ... 131  97  98]
  [ 75  78  81 ... 160 104  99]
  [ 79  77  80 ... 125  82 100]]

 [[ 96  93 107 ... 100 105 104]
  [ 97  94  91 ... 103 100 101]
  [ 98  93  91 ... 108  94  98]
  ...
  [108  98  99 ... 132 105 107]
  [ 96  99 101 ... 164 117 112]
  [ 99  98 100 ... 128  91 106]]

 [[ 72  70  80 ...  74  80  77]
  [ 74  70  68 ...  79  77  80]
  [ 75  71  65 ...  86  73  74]
  ...
  [ 89  79  79 ... 121  91  94]
  [ 76  80  81 ... 154 100  97]
  [ 79  78  80 ... 115  74  92]]]
tensor([1])


### Multi-label dataset 

In [3]:
data_multilabel = dataloader.ClassificationDataset(infer_list, dataset_root=dataset_root, binary=False)
num_classes_multi_label = data_multilabel.label_list.shape[1]
print("Amount of images", len(data_multilabel))
for img in tqdm(data_multilabel):
    print(img["name"])
    print(img["img"])
    print(img["label"])
    break

  0%|          | 0/547 [00:00<?, ?it/s]

Amount of images 547
3456.png
[[[ 70  72  70 ...  78  83  83]
  [ 71  67  68 ...  81  79  81]
  [ 72  68  62 ...  89  78  81]
  ...
  [ 88  78  80 ... 131  97  98]
  [ 75  78  81 ... 160 104  99]
  [ 79  77  80 ... 125  82 100]]

 [[ 96  93 107 ... 100 105 104]
  [ 97  94  91 ... 103 100 101]
  [ 98  93  91 ... 108  94  98]
  ...
  [108  98  99 ... 132 105 107]
  [ 96  99 101 ... 164 117 112]
  [ 99  98 100 ... 128  91 106]]

 [[ 72  70  80 ...  74  80  77]
  [ 74  70  68 ...  79  77  80]
  [ 75  71  65 ...  86  73  74]
  ...
  [ 89  79  79 ... 121  91  94]
  [ 76  80  81 ... 154 100  97]
  [ 79  78  80 ... 115  74  92]]]
tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Multi-label dataset (filtering out classes)

In [4]:
data_multilabel = dataloader.ClassificationDataset(infer_list, dataset_root=dataset_root, binary=False, classes = [1,2, 6])
num_classes_multi_label = data_multilabel.label_list.shape[1]
print("Amount of images", len(data_multilabel))
for img in tqdm(data_multilabel):
    print(img["name"])
    print(img["img"])
    print(img["label"])
    break

  0%|          | 0/354 [00:00<?, ?it/s]

Amount of images 354


  0%|          | 0/354 [00:00<?, ?it/s]

3456.png
[[[ 70  72  70 ...  78  83  83]
  [ 71  67  68 ...  81  79  81]
  [ 72  68  62 ...  89  78  81]
  ...
  [ 88  78  80 ... 131  97  98]
  [ 75  78  81 ... 160 104  99]
  [ 79  77  80 ... 125  82 100]]

 [[ 96  93 107 ... 100 105 104]
  [ 97  94  91 ... 103 100 101]
  [ 98  93  91 ... 108  94  98]
  ...
  [108  98  99 ... 132 105 107]
  [ 96  99 101 ... 164 117 112]
  [ 99  98 100 ... 128  91 106]]

 [[ 72  70  80 ...  74  80  77]
  [ 74  70  68 ...  79  77  80]
  [ 75  71  65 ...  86  73  74]
  ...
  [ 89  79  79 ... 121  91  94]
  [ 76  80  81 ... 154 100  97]
  [ 79  78  80 ... 115  74  92]]]
tensor([1, 0, 0])
